### 0. Importer pandas

**Déf :** `Pandas est une bibliothèque open-source du langage Python conçue pour la manipulation et l'analyse de données. Elle permet de travailler facilement avec des données tabulaires (lignes et colonnes), un peu comme un tableau Excel ou une table SQL`

In [194]:
import pandas as pd

### 1.1 Création de la Series

La fonction `pd.Series()` permet de créer une Series à partir d'une liste de valeurs.

Chaque élément de la liste devient une valeur de la series et reçoit automatiquement un index.

In [195]:
temperatures = pd.Series([24.5, 26.1, 25.8, 27.3])

temperatures

0    24.5
1    26.1
2    25.8
3    27.3
dtype: float64

### 1.2 Afficher l'index de la Series

L'index permet d'identifier chaque valeur d'une Series.

Par défaut, Pandas crée automatiquement un index numérique commençant à `0`.

In [196]:
temperatures.index

RangeIndex(start=0, stop=4, step=1)

### 1.3 Afficher la première valeur

La méthode `iloc[]` permet d'accéder à un élément selon sa position.

La première valeur d'une Series se trouve à la position `0`.

In [197]:
temperatures.iloc[0]

np.float64(24.5)

### 1.4 Afficher la dernière valeur

Pour accéder au dernier élément d'une Series, on utilise l'indice `-1`.

Cette méthode fonctionne quelle que soit la taille de la Series.

In [198]:
temperatures.iloc[-1]

np.float64(27.3)

### 1.5 Créer une series avec un index personnalisé (méthode 1)

Il est possible de définir un index personnalisé lors de la création d'une series.

Chaque température est ici associée à son heure de mesure.

In [199]:
temperatures_horaires = pd.Series(
    data=[24.5, 26.1, 25.8, 27.3],
    index=["12h", "13h", "14h", "15h"]
)

temperatures_horaires

12h    24.5
13h    26.1
14h    25.8
15h    27.3
dtype: float64

### 1.5 Créer une series avec un index personnalisé (méthode 2)

Une autre approche consiste à créer la series, puis à modifier son index après sa création.

Chose qui produit le même résultat que la précédente.

In [200]:
temperatures_horaires_2 = pd.Series([24.5, 26.1, 25.8, 27.3])

temperatures_horaires_2.index = ["12h", "13h", "14h", "15h"]

temperatures_horaires_2

12h    24.5
13h    26.1
14h    25.8
15h    27.3
dtype: float64

### 1.6 Afficher la première et la dernière valeur

Même avec un index personnalisé, `iloc[]` permet d'accéder aux valeurs selon leur position.

La première valeur est à la position `0` et la dernière à la position `-1`.

In [201]:
print("Première valeur :", temperatures_horaires.iloc[0])
print("Dernière valeur :", temperatures_horaires.iloc[-1])

Première valeur : 24.5
Dernière valeur : 27.3

### 2.1 Créer et afficher un DataFrame

Un **DataFrame** est une structure de données bidimensionnelle composée de lignes et de colonnes.

Il peut être créé à partir d'un dictionnaire où chaque clé représente une colonne et chaque valeur une liste de données.

In [202]:
data = {
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}

df_test = pd.DataFrame(data)

df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

### 2.2 Importer le dataset

La fonction `read_csv()` permet de charger un fichier CSV dans un DataFrame.

Le fichier **mesures_capteurs.csv** est stocké dans le dossier `data`.

In [203]:
df = pd.read_csv("../data/mesures_capteurs.csv")

df

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

### 2.3 Afficher les dimensions du DataFrame df

La propriété `shape` retourne les dimensions d'un DataFrame.

Elle renvoie un tuple contenant le nombre de lignes et le nombre de colonnes.

In [204]:
df.shape

(605, 9)

### 3.1 Afficher les premières lignes

La méthode `head()` permet d'afficher les premières lignes d'un DataFrame.

Par défaut, elle affiche les **5 premières lignes**.

In [205]:
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

### 3.2 Afficher les 10 premières lignes

La méthode `head()` accepte un paramètre indiquant le nombre de lignes à afficher.

Ici, nous affichons les **10 premières lignes** du DataFrame.

In [206]:
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

### 3.3 Afficher les dernières lignes

La méthode `tail()` permet d'afficher les dernières lignes d'un DataFrame.

Par défaut, elle affiche les **5 dernières lignes**.

In [207]:
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

### 3.4 Afficher le nombre de lignes

La propriété `shape` permet d'obtenir les dimensions d'un DataFrame.

Le premier élément correspond au **nombre de lignes**.

In [208]:
df.shape[0]

605

### 3.5 Afficher le nombre de colonnes

Le second élément de la propriété `shape` correspond au **nombre de colonnes** du DataFrame.

In [209]:
df.shape[1]

9

### 3.6 Afficher les noms des colonnes

La propriété `columns` retourne la liste des colonnes présentes dans le DataFrame.

In [210]:
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='str')

### 3.7 Afficher les informations générales

La méthode `info()` fournit un résumé du DataFrame.

Elle affiche notamment le nombre de lignes, les types de données et les valeurs manquantes.

In [211]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 42.7 KB

### 3.8 Afficher les statistiques descriptives

La méthode `describe()` calcule automatiquement les principales statistiques des colonnes numériques.

Elle affiche notamment la moyenne, l'écart-type, les valeurs minimales et maximales ainsi que les quartiles.

In [212]:
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

### 4.1 Sélectionner la colonne `temperature`

Il est possible de sélectionner une seule colonne d'un DataFrame en utilisant son nom.

Le résultat obtenu est une **Series**.

In [213]:
df["temperature"]

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

### 4.2 Sélectionner plusieurs colonnes

Pour sélectionner plusieurs colonnes, on utilise une liste contenant leurs noms.

Le résultat obtenu est un **DataFrame**.

In [214]:
df[["temperature", "humidite", "pression", "consommation"]]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

### 4.3 Sélectionner les 5 premières lignes avec `loc`

La méthode `loc[]` permet de sélectionner des lignes à partir de leurs labels.

Avec un index numérique par défaut, les labels correspondent aux numéros des lignes.

In [215]:
df.loc[:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

### 4.4 Sélectionner les 5 premières lignes et les 4 premières colonnes avec `iloc`

La méthode `iloc[]` permet de sélectionner des lignes et des colonnes selon leur position.

Ici, nous récupérons les cinq premières lignes et les quatre premières colonnes.

In [216]:
df.iloc[:5, :4]

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

### 5.1 Ajouter la colonne `temperature_fahrenheit`

Il est possible de créer une nouvelle colonne à partir d'une colonne existante.

La conversion de la température de **Celsius** vers **Fahrenheit** s'effectue avec la formule :

**F = (C × 9 / 5) + 32**

In [217]:
df["temperature_fahrenheit"] = (df["temperature"] * 9 / 5) + 32

df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat,temperature_fahrenheit
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,77.828
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,75.200
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,78.476
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,82.814
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,69.044

### 5.2 Ajouter la colonne `niveau_temperature`

La fonction `np.where()` permet de créer une nouvelle colonne en fonction d'une condition.

Une température supérieure à **30°C** sera considérée comme **"Élevée"**, sinon elle sera considérée comme **"Normale"**.

In [218]:
import numpy as np

df["niveau_temperature"] = np.where(
    df["temperature"] > 30,
    "Élevée",
    "Normale"
)

df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat,temperature_fahrenheit,niveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,77.828,Normale
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,75.200,Normale
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,78.476,Normale
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,82.814,Normale
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,69.044,Normale

### 5.3 Renommer la colonne `humidite`

La méthode `rename()` permet de modifier le nom d'une ou de plusieurs colonnes.

Ici, la colonne **humidite** est renommée en **humidite_relative**.

In [219]:
df.rename(
    columns={"humidite": "humidite_relative"},
    inplace=True
)

df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,temperature_fahrenheit,niveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,77.828,Normale
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,75.200,Normale
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,78.476,Normale
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,82.814,Normale
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,69.044,Normale

### 5.4 Supprimer la colonne `temperature_fahrenheit`

La méthode `drop()` permet de supprimer une ou plusieurs colonnes d'un DataFrame.

La colonne créée précédemment va etre retirées.

In [220]:
df.drop(
    columns="temperature_fahrenheit",
    inplace=True
)

df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,Normale
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,Normale
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,Normale
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,Normale
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,Normale

### 6.1 Récupérer les lignes où la température est supérieure à 30°C

Le filtrage permet de sélectionner uniquement les lignes qui respectent une condition.

Ici, nous affichons les mesures dont la température est strictement supérieure à **30°C**.

In [221]:
df[df["temperature"] > 30]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK,Élevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Élevée
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Élevée
63,M0064,2026-01-07 15:00:00,C004,B002,31.19,55.13,1011.04,264.98,OK,Élevée
79,M0275,2026-01-16 10:00:00,C011,B004,31.74,69.95,1020.79,335.89,OK,Élevée
88,M0288,2026-01-16 23:00:00,C012,B004,30.06,75.30,1014.47,323.32,OK,Élevée
103,M0311,2026-01-17 22:00:00,C011,B004,30.83,54.99,1026.47,256.11,OK,Élevée
112,M0149,2026-01-11 04:00:00,C005,B002,31.46,48.48,1002.75,210.94,OK,Élevée
118,M0365,2026-01-20 04:00:00,C005,B002,32.90,65.91,1027.28,246.08,ALERTE,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
137,M0076,2026-01-08 03:00:00,C004,B002,31.18,49.66,1019.91,215.22,OK,Élevée
145,M0503,2026-01-25 22:00:00,C011,B004,30.57,71.26,1002.88,359.97,OK,Élevée
146,M0118,2026-01-09 21:00:00,C010,B004,30.32,NaN,1015.78,261.68,OK,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée
168,M0276,2026-01-16 11:00:00,C012,B004,30.39,71.14,1017.79,303.38,OK,Élevée
169,M0546,2026-01-27 17:00:00,C006,B002,32.36,67.34,998.10,184.89,ALERTE,Élevée
174,M0405,2026-01-21 20:00:00,C009,B003,31.74,47.23,1015.59,115.79,OK,Élevée
210,M0588,2026-01-29 11:00:00,C012,B004,31.51,72.49,1018.21,307.97,OK,Élevée
211,M0370,2026-01-20 09:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE,Élevée
224,M0303,2026-01-17 14:00:00,C003,B001,30.84,67.98,1020.09,157.99,OK,Élevée
243,M0416,2026-01-22 07:00:00,C008,B003,30.16,54.00,1012.18,875.00,ERREUR,Élevée
246,M0312,2026-01-17 23:00:00,C012,B004,30.13,65.68,1009.70,198.65,OK,Élevée
251,M0114,2026-01-09 17:00:00,C006,B002,31.85,85.77,1013.56,237.21,ALERTE,Élevée
257,M0378,2026-01-20 17:00:00,C006,B002,31.99,66.32,1013.54,254.67,OK,Élevée
264,M0191,2026-01-12 22:00:00,C011,B004,30.75,71.35,1018.92,308.66,OK,Élevée
274,M0046,2026-01-06 21:00:00,C010,B004,30.92,67.19,1009.71,329.78,OK,Élevée
280,M0585,2026-01-29 08:00:00,C009,B003,31.30,73.35,1021.40,187.98,OK,Élevée
322,M0120,2026-01-09 23:00:00,C012,B004,30.19,53.58,1013.05,396.90,ALERTE,Élevée
356,M0574,2026-01-28 21:00:00,C010,B004,30.61,60.73,1022.32,321.75,OK,Élevée
362,M0396,2026-01-21 11:00:00,C012,B004,30.57,63.47,1017.40,248.36,OK,Élevée
385,M0126,2026-01-10 05:00:00,C006,B002,30.09,73.95,1007.24,162.39,OK,Élevée
398,M0514,2026-01-26 09:00:00,C010,B004,30.48,93.57,1015.93,306.24,ALERTE,Élevée
401,M0586,2026-01-29 09:00:00,C010,B004,31.44,63.10,996.56,271.51,OK,Élevée
404,M0598,2026-01-29 21:00:00,C010,B004,30.37,64.55,997.31,311.77,OK,Élevée
417,M0432,2026-01-22 23:00:00,C012,B004,30.38,65.98,1005.48,256.18,OK,Élevée
437,M0286,2026-01-16 21:00:00,C010,B004,32.16,41.80,996.99,255.56,ALERTE,Élevée
438,M0558,2026-01-28 05:00:00,C006,B002,32.56,67.77,1016.88,181.51,ALERTE,Élevée
447,M0170,2026-01-12 01:00:00,C002,B001,31.15,69.20,1016.10,172.49,OK,Élevée
488,M0431,2026-01-22 22:00:00,C011,B004,30.14,51.02,1007.70,366.53,ALERTE,Élevée
492,M0552,2026-01-27 23:00:00,C012,B004,30.24,62.06,1009.35,299.69,OK,Élevée
500,M0062,2026-01-07 13:00:00,C002,B001,30.39,52.13,1004.23,262.66,OK,Élevée
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
505,M0268,2026-01-16 03:00:00,C004,B002,30.34,64.23,1011.42,179.84,OK,Élevée
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Élevée
541,M0202,2026-01-13 09:00:00,C010,B004,30.86,76.00,1011.94,224.01,OK,Élevée
558,M0346,2026-01-19 09:00:00,C010,B004,30.68,36.33,1010.46,272.59,OK,Élevée

### 6.2 Récupérer les lignes où la température est supérieure à 30°C et l'humidité supérieure à 70%

Plusieurs conditions peuvent être combinées à l'aide des opérateurs logiques.

Ici, nous sélectionnons uniquement les mesures vérifiant les deux conditions.

In [222]:
df[
    (df["temperature"] > 30)
    & (df["humidite_relative"] > 70)
]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Élevée
88,M0288,2026-01-16 23:00:00,C012,B004,30.06,75.30,1014.47,323.32,OK,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
145,M0503,2026-01-25 22:00:00,C011,B004,30.57,71.26,1002.88,359.97,OK,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée
168,M0276,2026-01-16 11:00:00,C012,B004,30.39,71.14,1017.79,303.38,OK,Élevée
210,M0588,2026-01-29 11:00:00,C012,B004,31.51,72.49,1018.21,307.97,OK,Élevée
251,M0114,2026-01-09 17:00:00,C006,B002,31.85,85.77,1013.56,237.21,ALERTE,Élevée
264,M0191,2026-01-12 22:00:00,C011,B004,30.75,71.35,1018.92,308.66,OK,Élevée
280,M0585,2026-01-29 08:00:00,C009,B003,31.30,73.35,1021.40,187.98,OK,Élevée
385,M0126,2026-01-10 05:00:00,C006,B002,30.09,73.95,1007.24,162.39,OK,Élevée
398,M0514,2026-01-26 09:00:00,C010,B004,30.48,93.57,1015.93,306.24,ALERTE,Élevée
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
541,M0202,2026-01-13 09:00:00,C010,B004,30.86,76.00,1011.94,224.01,OK,Élevée

### 7.1 Trier les températures par ordre croissant

La méthode `sort_values()` permet de trier un DataFrame selon une ou plusieurs colonnes.

Les températures sont triées de la plus petite à la plus grande.

In [223]:
df_trie1 = df.sort_values(by="temperature")

df_trie1

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
487,M0538,2026-01-27 09:00:00,C010,B004,-18.50,66.27,1012.49,312.92,ERREUR,Normale
245,M0127,2026-01-10 06:00:00,C007,B003,14.11,145.00,1032.36,169.57,ERREUR,Normale
258,M0223,2026-01-14 06:00:00,C007,B003,15.49,47.96,1006.34,124.90,OK,Normale
249,M0175,2026-01-12 06:00:00,C007,B003,16.04,55.36,1005.68,140.95,OK,Normale
59,M0146,2026-01-11 01:00:00,C002,B001,16.77,53.44,1010.65,131.75,OK,Normale
...,...,...,...,...,...,...,...,...,...,...
163,M0019,2026-01-05 18:00:00,C007,B003,NaN,69.97,1014.14,181.07,OK,Normale
215,M0204,2026-01-13 11:00:00,C012,B004,NaN,59.96,1007.98,294.02,OK,Normale
513,M0490,2026-01-25 09:00:00,C010,B004,NaN,52.97,1010.71,253.63,OK,Normale
548,M0572,2026-01-28 19:00:00,C008,B003,NaN,68.63,1018.58,252.48,OK,Normale
556,M0092,2026-01-08 19:00:00,C008,B003,NaN,79.81,1007.05,113.00,OK,Normale

### 7.2 Trier les températures par ordre décroissant

En utilisant le paramètre `ascending=False`, le tri est effectué de la plus grande valeur vers la plus petite.

In [224]:
df_trie2 = df.sort_values(
    by="temperature",
    ascending=False
)

df_trie2

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
211,M0370,2026-01-20 09:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée
...,...,...,...,...,...,...,...,...,...,...
163,M0019,2026-01-05 18:00:00,C007,B003,NaN,69.97,1014.14,181.07,OK,Normale
215,M0204,2026-01-13 11:00:00,C012,B004,NaN,59.96,1007.98,294.02,OK,Normale
513,M0490,2026-01-25 09:00:00,C010,B004,NaN,52.97,1010.71,253.63,OK,Normale
548,M0572,2026-01-28 19:00:00,C008,B003,NaN,68.63,1018.58,252.48,OK,Normale
556,M0092,2026-01-08 19:00:00,C008,B003,NaN,79.81,1007.05,113.00,OK,Normale

### 7.3 Afficher les 10 températures les plus élevées

Après un tri décroissant, la méthode `head()` permet de récupérer les premières lignes du résultat.

Nous obtenons ainsi les **10 températures les plus élevées**.

In [225]:
top10 = df.sort_values(
    by="temperature",
    ascending=False
).head(10)

top10

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
211,M0370,2026-01-20 09:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée
118,M0365,2026-01-20 04:00:00,C005,B002,32.90,65.91,1027.28,246.08,ALERTE,Élevée
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Élevée
438,M0558,2026-01-28 05:00:00,C006,B002,32.56,67.77,1016.88,181.51,ALERTE,Élevée
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Élevée
169,M0546,2026-01-27 17:00:00,C006,B002,32.36,67.34,998.10,184.89,ALERTE,Élevée

### 7.4 Trier par bâtiment puis par température

Il est possible de trier un DataFrame selon plusieurs colonnes.

Les bâtiments sont triés par ordre croissant, tandis que les températures sont triées par ordre décroissant à l'intérieur de chaque bâtiment.

In [226]:
df.sort_values(
    by=["batiment", "temperature"],
    ascending=[True, False]
)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Élevée
447,M0170,2026-01-12 01:00:00,C002,B001,31.15,69.20,1016.10,172.49,OK,Élevée
224,M0303,2026-01-17 14:00:00,C003,B001,30.84,67.98,1020.09,157.99,OK,Élevée
500,M0062,2026-01-07 13:00:00,C002,B001,30.39,52.13,1004.23,262.66,OK,Élevée
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK,Normale
...,...,...,...,...,...,...,...,...,...,...
277,M0383,2026-01-20 22:00:00,C011,B004,20.60,71.17,1017.44,293.92,OK,Normale
338,M0060,2026-01-07 11:00:00,C012,B004,20.56,63.37,1004.50,256.18,OK,Normale
487,M0538,2026-01-27 09:00:00,C010,B004,-18.50,66.27,1012.49,312.92,ERREUR,Normale
215,M0204,2026-01-13 11:00:00,C012,B004,NaN,59.96,1007.98,294.02,OK,Normale
513,M0490,2026-01-25 09:00:00,C010,B004,NaN,52.97,1010.71,253.63,OK,Normale

### 8.1 Afficher la consommation moyenne par bâtiment

La méthode `groupby()` permet de regrouper les données selon une colonne.

Ici, nous calculons la consommation moyenne pour chaque bâtiment.

In [227]:
df.groupby("batiment")["consommation"].mean()

batiment
B001    177.870927
B002    221.785333
B003    153.191000
B004    282.552282
Name: consommation, dtype: float64

### 8.2 Afficher le minimum, le maximum, la moyenne et l'écart-type de la température par bâtiment

La méthode `agg()` permet d'appliquer plusieurs fonctions statistiques en une seule instruction.

Nous calculons ici les principales statistiques de la température pour chaque bâtiment.

In [228]:
df.groupby("batiment")["temperature"].agg(
    ["min", "max", "mean", "std"]
)

            min    max       mean       std
batiment
B001      16.77  32.72  23.578824  2.961211
B002      17.67  33.60  25.778000  2.951828
B003      14.11  31.74  23.013699  2.983902
B004     -18.50  58.70  27.119000  5.367361

### 8.3 Afficher le maximum et la moyenne de la température et de la consommation par bâtiment

Il est possible d'appliquer plusieurs fonctions statistiques sur plusieurs colonnes simultanément.

Cette approche permet d'obtenir une analyse plus complète.

In [229]:
df.groupby("batiment")[
    ["temperature", "consommation"]
].agg(["max", "mean"])

         temperature            consommation
                 max       mean          max        mean
batiment
B001           32.72  23.578824       294.72  177.870927
B002           33.60  25.778000       335.20  221.785333
B003           31.74  23.013699       875.00  153.191000
B004           58.70  27.119000       411.12  282.552282

### 8.4 Afficher la température moyenne globale

La méthode `mean()` calcule la moyenne d'une colonne numérique.

In [230]:
df["temperature"].mean()

np.float64(24.87831385642738)

### 8.5 Afficher la température maximale

La méthode `max()` retourne la valeur la plus élevée d'une colonne.

In [231]:
df["temperature"].max()

np.float64(58.7)

### 8.6 Afficher la consommation totale

La méthode `sum()` permet de calculer la somme des valeurs d'une colonne numérique.

In [232]:
df["consommation"].sum()

np.float64(125205.25)

### 8.7 Déterminer le bâtiment qui consomme le plus en moyenne

Après avoir calculé la consommation moyenne par bâtiment, la méthode `idxmax()` permet de retrouver celui dont la moyenne est la plus élevée.

In [233]:
df.groupby("batiment")["consommation"].mean().idxmax()

'B004'

### 8.8 Afficher le nombre d'alertes par bâtiment

Nous filtrons les lignes dont l'état est **ALERTE**, puis nous comptons le nombre d'occurrences pour chaque bâtiment.

In [234]:
df[df["etat"] == "ALERTE"].groupby("batiment").size()

batiment
B001     2
B002     7
B003     5
B004    15
dtype: int64

### 9.1 Afficher le nombre de valeurs manquantes par colonne

La méthode `isna()` permet de détecter les valeurs manquantes.

En la combinant avec `sum()`, on obtient le nombre de valeurs manquantes pour chaque colonne.

In [235]:
df.isna().sum()

id_mesure             0
date_heure            0
id_capteur            0
batiment              0
temperature           6
humidite_relative     5
pression              5
consommation          5
etat                  4
niveau_temperature    0
dtype: int64

### 9.2 Afficher le nombre total de valeurs manquantes

Après avoir compté les valeurs manquantes par colonne, il est possible d'obtenir le total en additionnant ces résultats.

In [236]:
df.isna().sum().sum()

np.int64(25)

### 9.3 Afficher le taux de valeurs manquantes

Le taux de valeurs manquantes permet de mesurer la proportion de données absentes dans chaque colonne.

Le résultat est exprimé en pourcentage.

In [237]:
(df.isna().mean() * 100).round(2)

id_mesure             0.00
date_heure            0.00
id_capteur            0.00
batiment              0.00
temperature           0.99
humidite_relative     0.83
pression              0.83
consommation          0.83
etat                  0.66
niveau_temperature    0.00
dtype: float64

### 9.4 Afficher les lignes contenant des valeurs manquantes

Le filtrage permet de retrouver uniquement les lignes comportant au moins une valeur manquante.

In [238]:
df[df.isna().any(axis=1)]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
14,M0056,2026-01-07 07:00:00,C008,B003,22.33,67.42,1014.41,101.20,NaN,Normale
30,M0073,2026-01-08 00:00:00,C001,B001,23.12,63.97,NaN,186.87,OK,Normale
91,M0473,2026-01-24 16:00:00,C005,B002,21.32,70.43,1021.20,194.76,NaN,Normale
128,M0300,2026-01-17 11:00:00,C012,B004,23.32,55.73,NaN,232.38,OK,Normale
139,M0345,2026-01-19 08:00:00,C009,B003,NaN,66.77,1015.33,216.31,OK,Normale
146,M0118,2026-01-09 21:00:00,C010,B004,30.32,NaN,1015.78,261.68,OK,Élevée
149,M0034,2026-01-06 09:00:00,C010,B004,28.91,NaN,1001.23,234.30,OK,Normale
163,M0019,2026-01-05 18:00:00,C007,B003,NaN,69.97,1014.14,181.07,OK,Normale
196,M0372,2026-01-20 11:00:00,C012,B004,29.33,56.91,1020.02,NaN,OK,Normale
215,M0204,2026-01-13 11:00:00,C012,B004,NaN,59.96,1007.98,294.02,OK,Normale
270,M0334,2026-01-18 21:00:00,C010,B004,29.63,67.70,1016.30,363.68,NaN,Normale
303,M0584,2026-01-29 07:00:00,C008,B003,23.78,64.66,NaN,153.81,OK,Normale
307,M0169,2026-01-12 00:00:00,C001,B001,21.86,51.83,NaN,195.72,OK,Normale
323,M0391,2026-01-21 06:00:00,C007,B003,21.82,NaN,1006.47,98.39,OK,Normale
459,M0143,2026-01-10 22:00:00,C011,B004,28.65,66.88,1001.41,NaN,OK,Normale
476,M0527,2026-01-26 22:00:00,C011,B004,26.16,NaN,1024.21,232.87,OK,Normale
490,M0227,2026-01-14 10:00:00,C011,B004,25.13,85.60,1011.20,NaN,ALERTE,Normale
491,M0449,2026-01-23 16:00:00,C005,B002,26.82,61.99,NaN,215.34,OK,Normale
511,M0506,2026-01-26 01:00:00,C002,B001,24.04,57.10,1014.04,NaN,OK,Normale
513,M0490,2026-01-25 09:00:00,C010,B004,NaN,52.97,1010.71,253.63,OK,Normale
526,M0015,2026-01-05 14:00:00,C003,B001,23.17,79.95,1006.07,NaN,OK,Normale
536,M0252,2026-01-15 11:00:00,C012,B004,27.01,NaN,1018.36,263.13,OK,Normale
548,M0572,2026-01-28 19:00:00,C008,B003,NaN,68.63,1018.58,252.48,OK,Normale
556,M0092,2026-01-08 19:00:00,C008,B003,NaN,79.81,1007.05,113.00,OK,Normale
572,M0190,2026-01-12 21:00:00,C010,B004,24.24,73.55,1018.12,299.91,NaN,Normale

### 9.5 Remplacer les valeurs manquantes de la température et de l'humidité

Les valeurs manquantes des colonnes **temperature** et **humidite_relative** sont remplacées par la moyenne de leur colonne.

Cette méthode permet de conserver les lignes tout en limitant l'impact des données manquantes.

In [239]:
df["temperature"] = df["temperature"].fillna(df["temperature"].mean())

df["humidite_relative"] = df["humidite_relative"].fillna(
    df["humidite_relative"].mean()
)

df[["temperature", "humidite_relative"]].isna().sum()

temperature          0
humidite_relative    0
dtype: int64

### 9.6 Remplacer les valeurs manquantes de la consommation

La médiane est moins sensible aux valeurs extrêmes que la moyenne.

Elle est utilisée ici pour remplacer les valeurs manquantes de la colonne **consommation**.

In [240]:
df["consommation"] = df["consommation"].fillna(
    df["consommation"].median()
)

df["consommation"].isna().sum()

np.int64(0)

### 9.7 Remplacer les valeurs manquantes de l'état

Les valeurs manquantes de la colonne **etat** sont remplacées par la chaîne de caractères **"INCONNU"**.

In [241]:
df["etat"] = df["etat"].fillna("INCONNU")

df["etat"].isna().sum()

np.int64(0)

### 10.1 Afficher le nombre de doublons

La méthode `duplicated()` permet d'identifier les lignes dupliquées.

En la combinant avec `sum()`, on obtient le nombre total de doublons présents dans le DataFrame.

In [242]:
df.duplicated().sum()

np.int64(5)

### 10.2 Afficher les doublons

Les lignes dupliquées peuvent être affichées en filtrant le DataFrame avec la méthode `duplicated()`.

In [243]:
df[df.duplicated()]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
183,M0599,2026-01-29 22:00:00,C011,B004,22.02,68.09,1005.90,227.81,OK,Normale
231,M0026,2026-01-06 01:00:00,C002,B001,22.87,77.99,1010.15,213.19,OK,Normale
355,M0147,2026-01-11 02:00:00,C003,B001,26.14,84.97,1003.59,142.31,OK,Normale
538,M0456,2026-01-23 23:00:00,C012,B004,20.68,72.69,1022.77,309.01,OK,Normale
539,M0302,2026-01-17 13:00:00,C002,B001,22.05,58.26,1007.30,140.42,OK,Normale

### 10.3 Supprimer les doublons puis vérifier la suppression

La méthode `drop_duplicates()` permet de supprimer les lignes dupliquées.

Une nouvelle vérification confirme que les doublons ont bien été supprimés.

In [244]:
df = df.drop_duplicates()

df.duplicated().sum()

np.int64(0)

### 11.1 Afficher les statistiques de la température

Les principales statistiques permettent de mieux comprendre la distribution des températures.

Nous affichons le minimum, le maximum, la moyenne, la médiane, l'écart-type et le nombre de valeurs.

In [245]:
print("Minimum :", df["temperature"].min())
print("Maximum :", df["temperature"].max())
print("Moyenne :", df["temperature"].mean())
print("Médiane :", df["temperature"].median())
print("Écart-type :", df["temperature"].std())
print("Nombre de valeurs :", df["temperature"].count())

Minimum : -18.5
Maximum : 58.7
Moyenne : 24.896033138564274
Médiane : 24.87831385642738
Écart-type : 4.048027092193241
Nombre de valeurs : 600

### 11.2 [1] Afficher le mode de la colonne `etat`

Le mode correspond à la valeur la plus fréquente d'une colonne.

La méthode `mode()` permet de l'obtenir.

In [246]:
df["etat"].mode()

0    OK
Name: etat, dtype: str

### 11.2 [2] Afficher le nombre de mesures par état

La méthode `value_counts()` compte le nombre d'occurrences de chaque valeur d'une colonne.

On obtient ainsi le nombre de mesures pour chaque état du capteur.

In [247]:
df["etat"].value_counts()

etat
OK         562
ALERTE      29
ERREUR       5
INCONNU      4
Name: count, dtype: int64

### 12.1 Exporter le DataFrame au format CSV

Une fois les données nettoyées, il est recommandé de les sauvegarder dans un nouveau fichier.

La méthode `to_csv()` permet d'exporter le DataFrame au format **CSV** dans le dossier `exports`.

In [248]:
df.to_csv(
    "../exports/donnees_nettoyees.csv",
    index=False
)

print("Export CSV réalisé avec succès.")

Export CSV réalisé avec succès.

### 12.2 Exporter le DataFrame au format JSON

Le format **JSON** est largement utilisé pour l'échange de données entre différentes applications.

La méthode `to_json()` permet d'exporter le DataFrame dans le dossier `exports`.

In [249]:
df.to_json(
    "../exports/donnees_nettoyees.json",
    orient="records",
    indent=4
)

print("Export JSON réalisé avec succès.")

Export JSON réalisé avec succès.